/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IBalancerZapOut } from "../IBalancerZapOut";

export class IBalancerZapOut__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBalancerZapOut {
    return new Contract(address, _abi, signerOrProvider) as IBalancerZapOut;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_ToTokenContractAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_FromBalancerPoolAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_IncomingBPT",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minTokensRec",
        type: "uint256",
      },
    ],
    name: "EasyZapOut",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];
