/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IBalancerZapOutInterface extends ethers.utils.Interface {
  functions: {
    "EasyZapOut(address,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "EasyZapOut",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "EasyZapOut", data: BytesLike): Result;

  events: {};
}

export class IBalancerZapOut extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IBalancerZapOutInterface;

  functions: {
    EasyZapOut(
      _ToTokenContractAddress: string,
      _FromBalancerPoolAddress: string,
      _IncomingBPT: BigNumberish,
      _minTokensRec: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "EasyZapOut(address,address,uint256,uint256)"(
      _ToTokenContractAddress: string,
      _FromBalancerPoolAddress: string,
      _IncomingBPT: BigNumberish,
      _minTokensRec: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  EasyZapOut(
    _ToTokenContractAddress: string,
    _FromBalancerPoolAddress: string,
    _IncomingBPT: BigNumberish,
    _minTokensRec: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "EasyZapOut(address,address,uint256,uint256)"(
    _ToTokenContractAddress: string,
    _FromBalancerPoolAddress: string,
    _IncomingBPT: BigNumberish,
    _minTokensRec: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    EasyZapOut(
      _ToTokenContractAddress: string,
      _FromBalancerPoolAddress: string,
      _IncomingBPT: BigNumberish,
      _minTokensRec: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "EasyZapOut(address,address,uint256,uint256)"(
      _ToTokenContractAddress: string,
      _FromBalancerPoolAddress: string,
      _IncomingBPT: BigNumberish,
      _minTokensRec: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    EasyZapOut(
      _ToTokenContractAddress: string,
      _FromBalancerPoolAddress: string,
      _IncomingBPT: BigNumberish,
      _minTokensRec: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "EasyZapOut(address,address,uint256,uint256)"(
      _ToTokenContractAddress: string,
      _FromBalancerPoolAddress: string,
      _IncomingBPT: BigNumberish,
      _minTokensRec: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    EasyZapOut(
      _ToTokenContractAddress: string,
      _FromBalancerPoolAddress: string,
      _IncomingBPT: BigNumberish,
      _minTokensRec: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "EasyZapOut(address,address,uint256,uint256)"(
      _ToTokenContractAddress: string,
      _FromBalancerPoolAddress: string,
      _IncomingBPT: BigNumberish,
      _minTokensRec: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
